    @Test
    public void bug51187() throws Exception {
        XMLSlideShow ss1 = openSampleDocument("51187.pptx");

        assertEquals(1, ss1.getSlides().size());

        // Check the relations on it
        // Note - rId3 is a self reference
        XSLFSlide slide0 = ss1.getSlides().get(0);

        assertRelation(slide0, "/ppt/slides/slide1.xml", null);
        assertRelation(slide0, "/ppt/slideLayouts/slideLayout12.xml", "rId1");
        assertRelation(slide0, "/ppt/notesSlides/notesSlide1.xml", "rId2");
        assertRelation(slide0, "/ppt/slides/slide1.xml", "rId3");
        assertRelation(slide0, "/ppt/media/image1.png", "rId4");

        // Save and re-load
        XMLSlideShow ss2 = XSLFTestDataSamples.writeOutAndReadBack(ss1);
        ss1.close();
        assertEquals(1, ss2.getSlides().size());

        slide0 = ss2.getSlides().get(0);
        assertRelation(slide0, "/ppt/slides/slide1.xml", null);
        assertRelation(slide0, "/ppt/slideLayouts/slideLayout12.xml", "rId1");
        assertRelation(slide0, "/ppt/notesSlides/notesSlide1.xml", "rId2");
        // TODO Fix this
        assertRelation(slide0, "/ppt/slides/slide1.xml", "rId3");
        assertRelation(slide0, "/ppt/media/image1.png", "rId4");

        ss2.close();
    }

