    @Test
    void testRefArraySum() throws IOException {
        refArrayFunctionTest("SUM");
    }

